# Generated by Django 3.1.1 on 2020-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('option1', models.CharField(max_length=100, null=True)),
                ('option2', models.CharField(max_length=100, null=True)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('correctAns', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
