# Generated by Django 3.1.1 on 2020-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tag',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
